### ISSUE TITLE
DELETE / PUT / PATCH -  Net::HTTPServerException:  405 "Method Not Allowed "

### ISSUE THREAD

**Issue by nibygro** [bbtfr/evil-proxy#1]
Hi. When I trying to use DELETE / PUT / PATCH methods - I'v got a `Net::HTTPServerException:  405 "Method Not Allowed "` error. Could it be fixed?

**Comment by bbtfr** [comment]
Yes, it should be fixed, but I don't think I can do it recently, do you like to send a PR for this?

**Comment by nbulaj** [comment]
Hi @bbtfr. How do you think - it should be done in the `httpproxy.rb` for the `EvilProxy::HTTPProxyServer` or as a plugin like `async` (I call it '`REST`') ?

**Comment by bbtfr** [comment]
@nbulaj glad to hear you got interested into this.
I think it should be done in `EvilProxy::HTTPProxyServer`, as a built-in feature, `DELETE` and `PUT` are common used per my understanding.

**Comment by bbtfr** [comment]
Fixed in #1 by @nbulaj , thanks!
